all:
  children:
    passwordless_group:
      hosts:
        MainDB:
          ansible_host: 170.187.238.208
          ansible_password: testssh
          ansible_port: 22
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: testssh
          dest_ip: 172.105.56.93
          dest_pass: test123
          dest_user: test123
        iBankLive:
          ansible_host: 172.105.56.93
          ansible_password: test123
          ansible_port: 22
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: test123
          dest_ip: 170.187.238.208
          dest_pass: testssh
          dest_user: testssh
    ungrouped: {}
